# -*- coding: utf-8 -*-
"""DataHack_Datadivas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16REaaFSPfNFkT7jdG4BJKWVILWKZL9Uf
"""

import pandas as pd

df=pd.read_csv('/content/to_filter - Sheet1.csv')
print(df)

df.drop_duplicates(inplace=True)
columns_with_nulls = ['City', 'Date', 'Industry']
df.dropna(subset=columns_with_nulls, inplace=True)
print(df)

print(df.shape)

self_owned_investor_rows = df[df['Investors'] == 'Self Owned']
print(self_owned_investor_rows)

self_owned_investor_rows = df[df["Investor's Location"] == 'India']
print(self_owned_investor_rows)

df.drop("Profit_fin", axis=1, inplace=True)

df.drop("Valuation_fin", axis=1, inplace=True)

print("Column's Datatype")
print(df.dtypes)

columns_to_convert = ['Funding_Final', 'Revenue_final', 'Valuation']

for column in columns_to_convert:
    df[column] = pd.to_numeric(df[column], errors='coerce')

print(df)

print(df.info())

dimensions = df.shape
print("Number of rows:", dimensions[0])
print("Number of columns:", dimensions[1])

df['Industry'].unique()

df.to_csv('DataAnalysis.csv',index =False)

